### ISSUE TITLE
Can't run PhantomFlow

### ISSUE THREAD

**Issue by MatheMatrix** [Huddle/PhantomFlow#36]
Hi,

I'm new to node.js, so maybe this is my fault but I can't find it :(

I do following things to install PhantomFlow:

brew install node
git clone git clone https://github.com/Huddle/PhantomFlow.git
npm install
node test/test.js

Then it shows:
```javascript
PhantomJS is not installed? Try `npm install`
Parallelising 2 test files on 2 threads.

It broke, sorry. Threads aborted. Non-zero code (1) returned.

 A thread has completed.

It broke, sorry. Threads aborted. Non-zero code (1) returned.

 All the threads have completed.

Completed 0 tests in 0 seconds. 0 failed, 0 passed.
/Users/weiwang/opensource/PhantomFlow/node_modules/wrench/lib/wrench.js:249
        if (e.code !== 'EEXIST') throw e;
                                       ^
Error: ENOENT, no such file or directory '/Users/weiwang/opensource/PhantomFlow/test-results/report'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:751:18)
    at Object.exports.copyDirSyncRecursive (/Users/weiwang/opensource/PhantomFlow/node_modules/wrench/lib/wrench.js:246:12)
    at copyReportTemplate (/Users/weiwang/opensource/PhantomFlow/phantomflow.js:415:10)
    at ChildProcess.<anonymous> (/Users/weiwang/opensource/PhantomFlow/phantomflow.js:271:8)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1008:16)
    at Socket.<anonymous> (child_process.js:1176:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:476:12)
```

Then I run npm install again:
```javascript

> phantomjs@1.9.18 install /Users/weiwang/opensource/PhantomFlow/node_modules/phantomjs
> node install.js

Download already available at /var/folders/t7/qb22hwj15j7c9yph0xbt7s1c0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Extracting zip contents
Removing /Users/weiwang/opensource/PhantomFlow/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/t7/qb22hwj15j7c9yph0xbt7s1c0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1439752203893/phantomjs-1.9.8-macosx -> /Users/weiwang/opensource/PhantomFlow/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/weiwang/opensource/PhantomFlow/node_modules/phantomjs/lib/phantom/bin/phantomjs
```

But it still not work :( just output as I paste first

**Comment by unional** [comment]
Are you using npm@3 or npm@2? I have same problem with 3 and created a fix for it.

**Comment by unional** [comment]
I have the same problem too.

**Comment by MatheMatrix** [comment]
➜  ~  npm -v
2.5.1
➜  ~  node -v
v0.12.0

**Comment by chris-dura** [comment]
@MatheMatrix 

So, I'm on Mac OSX Yosemite, and these versions seem to work...
```

Don't know if you're on Mac OSX, or if it will fix your problems, but people have experienced problems [installing/updating NPM with Homebrew](https://gist.github.com/DanHerbert/9520689)
