### ISSUE TITLE
Error running node test/test.js report

### ISSUE THREAD

**Issue by scibert** [Huddle/PhantomFlow#43]
Hi, 

**README.md** mentions that you can run `node test/test.js report` to load the Decision tree visualisation into your Web browser, but I get the following error:

```
D:\Learning\PhantomFlow\phantomflow.js:600
                log( "A report hasn't been generated.  Maybe you haven't set the
 createRepor
                ^
ReferenceError: log is not defined
    at showReport (D:\Learning\PhantomFlow\phantomflow.js:600:3)
    at Object.report (D:\Learning\PhantomFlow\phantomflow.js:112:9)
    at Object.<anonymous> (D:\Learning\PhantomFlow\test\test.js:40:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```
Might this be a bug? If not, any idea how to resolve this?

Note that running `node test/test.js` and `node test/test.js dashboard` works for me.

**Comment by meltuhamy** [comment]
Hi @scibert, thanks for reporting this. We've pushed a patch to fix this (0.5.8) so try updating.
